version: '3'

services:
  redis:
    container_name: redis-image
    image: redis:latest
    ports:
      - 6379:6379
    restart: "always"

  app:
    container_name: rinex-qa-backend
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 8000:8000
    volumes:
      - /tmp:/app/tmp
    restart: "always"
